openapi: 3.0.0
info:
  title: SOFTTEK
  version: 1.0.0
servers:
  - url: http://{{base_url}}
paths:
  /models:
    post:
      tags:
        - default
      summary: Create model and change attributes of english to spanish
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: people
                id: 3
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Get all models saved on DinamyDB
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}